apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: todo-app-prod
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
scopes:
- todo-backend
- event-service
